apiVersion: v1
kind: Pod
metadata:
  name: curl-tester
  labels:
    app: curl-tester
spec:
  containers:
    - name: curl-container
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          memory: "64Mi"
          cpu: "250m"
